<style>
    body .price span.festi-user-role-prices-regular-price-lable,
    body .price span.festi-user-role-prices-user-price-lable,
    body .price span.festi-user-role-prices-discount-lable,
    body .order-total span.festi-user-role-prices-regular-price-lable,
    body .order-total span.festi-user-role-prices-user-price-lable,
    body .order-total span.festi-user-role-prices-discount-lable
    {
        color: <?php echo $settings['customerSavingsLableColor']; ?>;
    }
</style>