<tr class="wholesale_price_row">
    <td>
        <div>
            <?php

               $id = 'festiVariableUserRolePrices_'.$loop.'_'.$key;
            ?>
            <p class="form-field <?php echo  $id; ?>_field ">
                <label for="<?php echo  $id; ?>">
                    <?php echo  $label; ?>
                </label>
                <input type="text" class="short wc_input_price" name="festiVariableUserRolePrices[<?php echo  $loop; ?>][<?php echo  $key; ?>]" id="<?php echo  $id; ?>" value="" placeholder="">
            </p>
        </div>
    </td>
</tr>