<div class="custom_field_settings field_settings">
    <h4><?php _e('Custom Field Settings', $this->_languageDomain); ?></h4>
    <p>
        <label for="custom_field_name_<?php echo $id; ?>">
    		<?php _e(
        		 'Name',
        		 $this->_languageDomain
			 ); ?>
		 </label>
        <input type="text" name="custom_field_name[<?php echo $id; ?>]" 
        	id="custom_field_name_<?php echo $id; ?>" 
        	value="<?php echo ($isFirstRowHeader) ? $firstRow[$id] : ''; ?>" />
    </p>
    
    <p>
        <input type="checkbox" name="custom_field_visible[<?php echo $id; ?>]"
        	 id="custom_field_visible_<?php echo $id; ?>"
        	  value="1" checked="checked" />
        <label for="custom_field_visible_<?php echo $id; ?>">
        	<?php _e(
	        	 'Visible?',
	        	 $this->_languageDomain
			 ); ?>
		 </label>
    </p>
</div>

<div class="product_image_settings field_settings">
    <h4>
		<?php _e(
			 'Image Settings',
			 $this->_languageDomain
		 ); ?>
	 </h4>
    <p>
        <input type="checkbox"
        	  name="product_image_set_featured[<?php echo $id; ?>]"
        	  id="product_image_set_featured_<?php echo $id; ?>" 
        	  value="1" checked="checked" />
        <label for="product_image_set_featured_<?php echo $id; ?>">
        		<?php _e(
        			 'Set First Image as Featured',
        			 $this->_languageDomain
				 ); ?>
		 </label>
    </p>
    <p>
        <input type="checkbox" 
        	 name="product_image_skip_duplicates[<?php echo $id; ?>]" 
        	 id="product_image_skip_duplicates_<?php echo $id; ?>"
        	 value="1" checked="checked" />
        <label for="product_image_skip_duplicates_<?php echo $id; ?>">
        		<?php _e('Skip Duplicate Images',
        		 $this->_languageDomain
			 ); ?>
	 	</label>
    </p>
</div>

<div class="post_meta_settings field_settings">
    <h4>
		<?php _e(
			 'Post Meta Settings',
			 $this->_languageDomain
		 ); ?>
 	</h4>
    <p>
        <label for="post_meta_key_<?php echo $id; ?>">
        	<?php _e(
        		'Meta Key', $this->_languageDomain
			); ?>
		</label>
        <input type="text"
        	   name="post_meta_key[<?php echo $id; ?>]"
        	   id="post_meta_key_<?php echo $id; ?>"
        	   value="<?php echo ($isFirstRowHeader) ? $firstRow[$id] : ''; ?>"/>
    </p>
</div>